name: Run FS25 Logs Analyzer

on:
  schedule:
    - cron: '0 3 * * *'  # codziennie o 3:00 UTC
  workflow_dispatch:     # ręczne uruchomienie z GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run analyzer
        run: |
          python logs_analyzer.py

      - name: Commit updated index.html
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html
          git commit -m "Auto update $(date)"
          git push
