name: Run FS25 Logs Analyzer

on:
  schedule:
    - cron: '0 3 * * *'  # codziennie o 3:00 UTC
  workflow_dispatch:     # ręczne uruchomienie z GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'
          architecture: 'x64'

      - name: Check Python version and path
        run: |
          which python
          which python3
          python --version
          python3 --version

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Run analyzer
        run: |
          set -x
          python3 logs_analyzer.py

      - name: Commit updated index.html
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html
          git commit -m "Auto update $(date)" || echo "No changes to commit"
          git push
